### ISSUE TITLE
Stack trace broken on version 2.1.2

### ISSUE THREAD

**Issue by nfroidure** [SimpliField/yerror#14]
Suddenly there is no more stack trace in my project when accessing the `.stack` property.
```
node                                 
> require('yerror').wrap(new (require('yerror'))('E_T', 1, 2)).stack
capture Error: E_T: E_T
capture Error: E_T: E_T
'Error: E_T: E_T'
```
With the non-built files
```
> require('yerror/src').wrap(new (require('yerror/src'))('E_T', 1, 2)).stack
'YError: E_T (1, 2): E_T\n    at repl:1:28\n    at ContextifyScript.Script.runInThisContext (vm.js:50:33)\n    at REPLServer.defaultEval (repl.js:240:29)\n    at bound (domain.js:301:14)\n    at REPLServer.runBound [as eval] (domain.js:314:12)\n    at REPLServer.onLine (repl.js:468:10)\n    at emitOne (events.js:121:20)\n    at REPLServer.emit (events.js:211:7)\n    at REPLServer.Interface._onLine (readline.js:282:10)\n    at REPLServer.Interface._line (readline.js:631:8)\nYError: E_T (): E_T\n    at Function.yerrorWrap [as wrap] (/home/nfroidure/sencrop/infrastructure-sencrop/node_modules/yerror/src/index.js:60:12)\n    at repl:1:23\n    at ContextifyScript.Script.runInThisContext (vm.js:50:33)\n    at REPLServer.defaultEval (repl.js:240:29)\n    at bound (domain.js:301:14)\n    at REPLServer.runBound [as eval] (domain.js:314:12)\n    at REPLServer.onLine (repl.js:468:10)\n    at emitOne (events.js:121:20)\n    at REPLServer.emit (events.js:211:7)\n    at REPLServer.Interface._onLine (readline.js:282:10)'
> require('yerror/src').wrap(new (require('yerror/src'))('E_T', 1, 2)).stack
'YError: E_T (1, 2): E_T\n    at repl:1:28\n    at ContextifyScript.Script.runInThisContext (vm.js:50:33)\n    at REPLServer.defaultEval (repl.js:240:29)\n    at bound (domain.js:301:14)\n    at REPLServer.runBound [as eval] (domain.js:314:12)\n    at REPLServer.onLine (repl.js:468:10)\n    at emitOne (events.js:121:20)\n    at REPLServer.emit (events.js:211:7)\n    at REPLServer.Interface._onLine (readline.js:282:10)\n    at REPLServer.Interface._line (readline.js:631:8)\nYError: E_T (): E_T\n    at Function.yerrorWrap [as wrap] (/home/nfroidure/sencrop/infrastructure-sencrop/node_modules/yerror/src/index.js:60:12)\n    at repl:1:23\n    at ContextifyScript.Script.runInThisContext (vm.js:50:33)\n    at REPLServer.defaultEval (repl.js:240:29)\n    at bound (domain.js:301:14)\n    at REPLServer.runBound [as eval] (domain.js:314:12)\n    at REPLServer.onLine (repl.js:468:10)\n    at emitOne (events.js:121:20)\n    at REPLServer.emit (events.js:211:7)\n    at REPLServer.Interface._onLine (readline.js:282:10)'
```

I think the tests passed since in the built version of the tests, you still require the `../src/index` file.

**Comment by nfroidure** [comment]
This may be useful for you, looks like there is a babel plugin that specifically deal with this problem: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error#ES6_Custom_Error_Class

**Comment by SebastienElet** [comment]
Nice catch, thanks !

Can you review my PR please ? then i will merge and publish a new release.

**Comment by SebastienElet** [comment]
The version v2.1.3 is now published on npm.

@nfroidure please tell us if you have any issue with this version
